FROM python:3.10-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8000

WORKDIR /app

# Install requirements
COPY requirements-barebones.txt .
RUN pip install --no-cache-dir -r requirements-barebones.txt && \
    rm -rf /root/.cache

# Copy only the necessary files
COPY ./app/main_barebones.py ./main.py

# Use this simple CMD (no variable substitution needed)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]