# news-rag-backend/docker-compose.yml
version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.2 # Specify a recent stable version
    container_name: qdrant_news_rag
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # HTTP REST API port (useful for direct inspection)
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persist Qdrant data locally
    # For production, you'd configure API keys, etc.
    # environment:
    #   QDRANT__SERVICE__API_KEY: "your-secret-api-key" # Example, not needed for local if not set in Qdrant config

  redis:
    image: redis:7.2-alpine # Specify a recent stable version
    container_name: redis_news_rag
    ports:
      - "6379:6379" # Default Redis port
    volumes:
      - ./redis_data:/data # Persist Redis data locally (optional for dev, but good practice)
    command: redis-server --save 60 1 --loglevel warning # Save RDB snapshot every 60s if at least 1 key changed

volumes:
  qdrant_storage: # Defines the named volume for Qdrant
  redis_data: # Defines the named volume for Redis
